---
name: Main
on:
  push:
    branches: [$default-branch]
jobs:
  build-push-gcp:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    steps:
      - name: Build and Push to GCP Artifact Registry
        uses: latrock/build-and-push-to-gcp-artifact-registry@v0.1.3
        with:
          gcp-sa-creds-json: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          registry: europe-west3-docker.pkg.dev
          repository: fixme
          image-name: fixme
